#server:
#  port: 8090

spring:
  application:
    name: gateway-services
  cloud:
    gateway:
      routes:
        - id: courses-services
          uri: lb://courses-services # name service kubernetes
          predicates:
            - Path=/api/courses/**
          filters:
            - RewritePath=/api/courses/(?<segment>.*), /courses-services/$\{segment}
        - id: users-services
          uri: lb://users-services
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /users-services/$\{segment}