apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-services-deployment-name # name deployment
  labels:
    app: gateway-services-deployment-label # este nombre se hace referencia en el service de kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-services-selector # este nombre se hace referencia en el pod (linea 15), y en el service de kubernetes
  template:
    metadata:
      labels:
        app: gateway-services-selector # debe ser igual a la linea 11
    spec:
      containers:
        - name: gateway-services-container # name container
          image: angelnpo/gateway-services:1.0.0-SNAPSHOT
          ports:
            - containerPort: 8090