apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-services-deployment-label # Debe ser el mismo de deployment-gateway-services.yaml (ver linea 6)
  name: gateway-services # nombre que se utiliza como host del pod para conectarse. Ejemplo (otros pods, postman, ect)
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: gateway-services-selector # debe ser el mismo label del pod (ver linea 11 del deployment-gateway-services.yaml)
  type: LoadBalancer
